### ISSUE TITLE
Directives have to be defined in @NgModule declarations since RC6.

### ISSUE THREAD

**Issue by flokixdev** [previousdeveloper/angular2-simple-countdown#2]

**Comment by flakerimi** [comment]
This has been fixed with #3

**Comment by ccinar91** [comment]
Couldn't make this work. npm install doesn't create "./countdown" or anything inside node_modules. Can anyone tell me what to do to make this work?

**Comment by previousdeveloper** [comment]
i will check it

**Comment by flakerimi** [comment]
Currently I am saving countdown.ts component on same dir I am going to use.

**Comment by previousdeveloper** [comment]
import {CountDown} from "../../node_modules/angular2-simple-countdown/countdown";

@NgModule({
  declarations: [
    CountDown
  ],
  ....

  })

?

**Comment by previousdeveloper** [comment]
fixed
