### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by flakerimi** [previousdeveloper/angular2-simple-countdown#4]
How do you change Days, hours ... in other language.

**Comment by previousdeveloper** [comment]
You can make custom content like that.

text: any = { "Weeks": "Weeks", 
    "Days": "Days", "Hours": "Hours",
     Minutes: "Minutes", "Seconds": "Seconds",
    "MilliSeconds":"MilliSeconds" };

 [text]="text" units="Days | Hours | Minutes | Seconds | Milliseconds" end="February 222016">
