### ISSUE TITLE
Using in Ionic

### ISSUE THREAD

**Issue by davorpeic** [previousdeveloper/angular2-simple-countdown#8]
Hi,
I imported this in Ionic app (3.5.0) and I get this error
`platform-browser-dynamic.es5.js:170 Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open 'path-to-app/node_modules/angular2-simple-countdown/countdown.js'`

Can you include js built file?
davor

**Comment by ttibau** [comment]
Did you solved it?

**Comment by davorpeic** [comment]
@ttibau Hi, no, I later upgraded from ionic->nativescript and I used https://github.com/urish/ngx-moment to manage what I needed with custom pipes..
